### ISSUE TITLE
Qunit forces browser to always scroll top on page load

### ISSUE THREAD

**Issue by SimonHarte** [MarcDiethelm/xtc#25]
Even if testing results are only shown in console, qunit has a code snippet which forces the browser to always scroll to top. This is very annoying when developing a page.

Starting at line 1277:

``` javascript
    // scroll back to top to show results
    if ( window.scrollTo ) {
        window.scrollTo(0, 0);
    }
```

**Comment by MarcDiethelm** [comment]
Here's the issue at Qunit: jquery/qunit/issues/414
