### ISSUE TITLE
Use LessCSS @import (reference)

### ISSUE THREAD

**Issue by MarcDiethelm** [MarcDiethelm/xtc#45]
As described in https://github.com/assemble/assemble-less/issues/13#issuecomment-23212069 Because it's totally awesome.

Library folders will be configured to be included like this. Needs docs.

**Comment by SimonHarte** [comment]
With the new folder structure, less files in lib/reference aren't watched by grunt.

**Comment by MarcDiethelm** [comment]
Jep. Fixed in 0.7.0
