### ISSUE TITLE
Dummy text helper

### ISSUE THREAD

**Issue by frogger1403** [MarcDiethelm/xtc#47]
It would be nice to have a "Lorem ipsum" dummy text generator, that generates dummy text in the given length.

For example:
{{ w(3) }} -> Lorem ipsum amet

Thanks
Heiko

**Comment by MarcDiethelm** [comment]
I would propose a syntax like this:

```
{{lorem 3}}
```

or maybe more generic

```
{{filler 3}} // shorthand produces same output as "lorem" below
{{filler 3 "lorem"}}
{{filler 42 "hamlet"}}
```

The "generic" syntax would allow for different text output.
Finally the deluxe implementation:

```
{{filler 42 "hamlet" "richtext"}}
```

This would produce Shakespeare text wrapped in some common richtext markup like headings, lists, tables, blockquotes and so on.

What do you think?

**Comment by frogger1403** [comment]
I definitively would go for the generic approach. I like the idea of different texts, please do not forget to add a possibility to add links to the text.

Thank you,
Heiko

**Comment by MarcDiethelm** [comment]
Very good. I'll implement this functionality for 0.8 as a Handlebars helper and publish it on npm and bower so that others can benefit from it too. This will be a fun project!

**Comment by MarcDiethelm** [comment]
The first version is now available.
https://github.com/MarcDiethelm/Hipsum.js
