### ISSUE TITLE
EMFILE error while parsing less / Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by MarcDiethelm** [MarcDiethelm/xtc#58]
In a somewhat large project developed by users of xtc the less parser fails because too many files (@imports) are open. So far it only happens after the initial grunt pass when triggered by the file watcher and in the mac terminal where `ulimit -n` reports 256 (max open files). http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me

Why does this only happen when started by the watch task? Are files not being closed the should be?

less.js unfortunately does not handle the error and fails because the expected data is undefined. https://github.com/less/less.js/issues/1106#issuecomment-28204157

**Comment by dmodalek** [comment]
Increasing ulimit did it for me, thank you!

$ ulimit -n 8192

**Comment by MarcDiethelm** [comment]
Fixed upstream
