### ISSUE TITLE
`npm run build` fails if there are empty folders in sprites folder

### ISSUE THREAD

**Issue by jackblackCH** [MarcDiethelm/xtc#72]

**Comment by MarcDiethelm** [comment]
xtc is using grunt-glue-nu to prevent this kind of error, so this should not be happening.
Please provide the full error output, xtc version and glue version. Thank you very much.

**Comment by jackblackCH** [comment]
I had an image with the same name in a subfolder and didn't realize the error message on the top of the output. /close

**Comment by MarcDiethelm** [comment]
You can comment on issues even when they are closed btw.
