### ISSUE TITLE
mod helper: indent attribute - buggy output (when value is string)

### ISSUE THREAD

**Issue by jackblackCH** [MarcDiethelm/xtc#75]
If you use the indent attribute on the mod helper.
i.e
{{mod "my-mod" indent="10"}}

the printed markup is buggy -  not valid. contains suspicious numbers without any tags.

**Comment by MarcDiethelm** [comment]
Can you give an example of the output you're seeing, thanks.

**Comment by jackblackCH** [comment]
Ok, found out:

If you add the indent value as a string
`{{mod "my-mod" indent="10"}}` the output is buggy ( [Gist](https://gist.github.com/jackblackCH/83696091331885869f29) )
look at the numbers on the left side ( not the line numbers )

If you add as integer, it works.
`{{mod "my-mod" indent=10}}`

**Comment by MarcDiethelm** [comment]
I'll try to handle this user error better. Thanks for the report.

**Comment by MarcDiethelm** [comment]
In any case the [documentation](https://github.com/MarcDiethelm/xtc/blob/master/Documentation.md#terrific-modules) tells you to use integer values.

I added some type checking and error output to prevent this mistake in the future.
